### ISSUE TITLE
Signal handling causes stream_select to fail

### ISSUE THREAD

**Issue by theseer** [hollodotme/fast-cgi-client#41] opened 2019-05-28 15:27 UTC
## Expected Behavior

Signal handling does not break the processing of outstanding responses.

## Actual Behavior

Sending a signal to the process causes PHP to emit a warning and fast-cgi-client to throw exceptions because of read time outs.

## Specifications

- Package version: 2.7.1
- PHP version: 7.3.5
- Platform/OS: Linux

## Further comments

When used in a long running PHP process and in combination with signal handling (e.g. `kill -15 <pid>`), the `Client`'s call to `stream_select`  [(line 247)](https://github.com/hollodotme/fast-cgi-client/blob/master/src/Client.php#L247) has a high chance of getting interrupted. That will make PHP emit a warning ("interrupted system call") as well as return false. 

This is actually the documented behavior of `stream_select` and has been an issue with many other PHP projects already when trying to combine sockets and signal handling. Looks like, we have it here now as well...

As temporary fix we modified [Client.php](https://github.com/hollodotme/fast-cgi-client/blob/master/src/Client.php#L247) to read:

```php
$result = @stream_select( $reads, $writes, $excepts, 0, Socket::STREAM_SELECT_USEC );

if ($result === false) {
    stream_select( $reads, $writes, $excepts, 0, Socket::STREAM_SELECT_USEC );
}
```

This code of course completely ignores other potential reasons for `stream_select` to fail so probably should check the reason in one way or another.

A quick google check turned up various comparable solutions in other PHP projects, which even include parsing the actual error message ;-):

- Symfony: https://github.com/symfony/process/blob/master/Pipes/AbstractPipes.php#L66
- ReactPHP: https://github.com/reactphp/event-loop/pull/44/files

Not sure what would be best here. The cleanest approach probably would be to register a custom error handler before calling `stream_select` - but that also comes with quite an overhead...

**Comment by hollodotme** [comment] 2019-05-30 22:37
After some investigation and the fix of #40, there was basically nothing to do here.
The method containing the `stream_select()` call only makes sense in a loop. In case `stream_select()` returns `false` the method `Client#getRequestIdsHavingResponse()` would return an empty array and in the next loop the method checks the streams again and may return something that indicates activity (good or bad).

The behavior that too many response and failure callbacks were called again was caused by the bug that was fixed in #40 (too many open connections that may already had responses).

In order to make it explicit in the code, I decided to go with this little change:

```php
public function getRequestIdsHavingResponse() : array
{
	if ( $this->sockets->isEmpty() )
	{
		return [];
	}

	$reads  = $this->sockets->collectResources();
	$writes = $excepts = null;

	$result = @stream_select( $reads, $writes, $excepts, 0, Socket::STREAM_SELECT_USEC );

	if ( false === $result || 0 === count( $reads ) )
	{
		return [];
	}

	return $this->sockets->getSocketIdsByResources( $reads );
}
```

I added some [integration tests](https://github.com/hollodotme/fast-cgi-client/blob/2.x-dev/tests/Integration/SignaledWorkersTest.php) that fire multiple async requests, killing single or multiple fpm processes and checking for the correct results in callbacks. In those tests I interrupt the fpm processes with the following signals:

* SIGHUP(1)
* SIGINT(2)
* SIGKILL(9)
* SIGTERM(15)

**Closed** 2019-05-30 23:04 UTC
Labels: confirmed, enhancement
